<?php
$form = $this->userForm->prepare();
?>

<div class="row">
    <div class="col-lg-6">
        <h1>Modifica utene: <?= $this->user->getName() . ' ' . $this->user->getSurname(); ?></h1>
    </div>

    <div class="col-lg-6">
        <a href="#" class="btn btn-primary pull-right" style="margin-top: 20px;">Torna Indietro</a>
    </div>
</div>


<div class="row">
    <div class="col-md-12">

        <?= $this->form()->openTag($form); ?>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender">Nome</label>
                    <?= $this->formRow($form->get('name')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Cognome</label>
                    <?= $this->formRow($form->get('surname')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Email</label>
                    <?= $this->formRow($form->get('email')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Ripeti Email</label>
                    <?= $this->formRow($form->get('email2')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender">Password</label>
                    <?= $this->formRow($form->get('password')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Ripeti Password</label>
                    <?= $this->formRow($form->get('password2')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender">Stato</label>
                    <?= $this->formRow($form->get('status')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Ruolo</label>
                    <?= $this->formRow($form->get('role')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success">Modifica Utente</button>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>
