<div class="row">
    <div class="col-lg-6">
        <h1>Lista Utenti</h1>
    </div>
    <div class="col-lg-6">
        <a href="<?= $this->url('admin/user/add'); ?>" class="btn btn-primary pull-right" style="margin-top: 20px;">Aggiunti Utente</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">

        <?= $this->partial('partials/flash-messages.phtml', []); ?>

        <table class="table table-hover">
            <thead>
            <tr>
                <th>Nome & Cognome</th>
                <th>Email</th>
                <th>Stato</th>
                <th>Ruolo</th>
                <th>Azioni</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \WebReattivoCore\Entity\User $user */
            foreach($this->users as $user): ?>
                <tr>
                    <th><?= $user->getName() . ' ' . $user->getSurname(); ?></th>
                    <th><?= $user->getEmail(); ?></th>
                    <td><?= $user->getStatus(); ?></td>
                    <td><?= $user->getRole(); ?></td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="<?= $this->url('admin/user/edit', ['id' => $user->getId()]); ?>" class="btn btn-sm btn-warning">Modifica</a>
                            <a href="#" class="btn btn-sm btn-danger">Elimina</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
