<h1>Registration</h1>
<?php
/** @var \Zend\Form\Form $form */
$form = $this->registrationForm->prepare();
?>

<div class="row">
    <div class="col-md-12">

        <?= $this->partial('partials/flash-messages.phtml', []); ?>

        <?= $this->form()->openTag($form); ?>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender">Nome</label>
                    <?= $this->formRow($form->get('name')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Cognome</label>
                    <?= $this->formRow($form->get('surname')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Email</label>
                    <?= $this->formRow($form->get('email')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Ripeti Email</label>
                    <?= $this->formRow($form->get('email2')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="gender">Password</label>
                    <?= $this->formRow($form->get('password')); ?>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Ripeti Password</label>
                    <?= $this->formRow($form->get('password2')); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success">Registrati</button>
            </div>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>
