<h1>Reset Password</h1>
<?php
if($this->statusToken):
    $form = $this->resetPwdFrom->prepare();
    ?>

    <div class="row">
        <div class="col-md-12">

            <?= $this->partial('partials/flash-messages.phtml', []); ?>

            <?= $this->form()->openTag($form); ?>

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="gender">Password</label>
                        <?= $this->formRow($form->get('password')); ?>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="gender">Ripeti Password</label>
                        <?= $this->formRow($form->get('password2')); ?>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-12">
                    <button type="submit" class="btn btn-success">Reset Password</button>
                </div>
            </div>

            <?= $this->form()->closeTag(); ?>

        </div>
    </div>

<?php else: ?>
    <?= $this->message; ?>
<?php endif; ?>


